tab_size: 4
keyword_case: upper
command_case: lower
separate_ctrl_name_with_space: false
line_width: 80
autosort: false
max_pargs_hwrap: 2
dangle_parens: true
per_command:
  target_sources:
    layout: stack
